apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.deploymentConfig.serviceAccount | default "nexus" }}-{{ .Values.serviceAccount.role | default "edit" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Values.serviceAccount.role | default "edit" | quote }}
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: {{ .Values.deploymentConfig.serviceAccount | default "nexus" | quote }}
    namespace: {{ .Release.namespace | quote }}