apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName | quote }}
  name: {{ .Values.appName | quote }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol | default "TCP" | quote }}
    targetPort: {{ .Values.service.port }}
  selector:
    name: {{ include "nexus.fullname" . }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" | quote }}
  type: {{ .Values.service.type | quote }}